### ISSUE TITLE
Chapter 1 files don't match the books!

### ISSUE THREAD

**Issue by cwgabel** [PacktPublishing/MEAN-Blueprints#2]
In Chapter 1, there is a "return next()" at the top of the function in app\middlewares\authentication.js  that prevents passport from authenticating. 

This repo for Chapter 1 has references to account that has nothing to do with Chapter 1. 

I have yet to get any of this code to run.  

Needs some work!

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
