### ISSUE TITLE
Unable to run chapter 5 sample

### ISSUE THREAD

**Issue by firefoxNX** [PacktPublishing/MEAN-Blueprints#3]
After copying the winston and environment configs when I run node server.js the node app does not start up without having a logs folder created. After creating logs folder the node app starts up but and when I navigate to localhost:3000 I see "Awesome Store" with green background. Is there a working version of the e-commerce code?

**Comment by techsachinkumar** [comment]
Hi firefoxNX,

It seems the code was meant only for explaination purpose and developed for the book.
If there was a working version, the link to it would be provided in the book.

Regards
